# Root-level Railway configuration
[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
# Let the nixpacks.toml file handle the build process
buildCommand = ""

[deploy]
startCommand = "cd packages/server/api && NODE_ENV=production node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

# Explicitly ensure Nixpacks is used and Dockerfile is disabled
[build.nixpacks]
enable = true

[build.dockerfile]
enable = false
path = ""

# Set environment variables
[variables]
NODE_ENV = "production"

# Add cron job from railway.json
[[crons]]
schedule = "*/30 * * * *"
command = "cd packages/server/api && yarn check-timeouts" 