# Root-level Railway configuration
[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
# We need to explicitly set the buildCommand to use our Corepack-enabled Yarn
buildCommand = "npm install -g corepack@0.24.1 && corepack enable && yarn install --mode update-lockfile && yarn workspace @wavenotes-new/shared build && yarn workspace @wavenotes-new/api build"

[deploy]
startCommand = "cd packages/server/api && NODE_ENV=production node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

# Explicitly ensure Nixpacks is used and Dockerfile is disabled
[build.nixpacks]
enable = true

[build.dockerfile]
enable = false
path = ""

# Set environment variables
[variables]
NODE_ENV = "production"

# Add cron job from railway.json
[[crons]]
schedule = "*/30 * * * *"
command = "cd packages/server/api && yarn check-timeouts" 