[phases.setup]
aptPkgs = ["git"]

# We need to properly set up Corepack for Yarn 4
[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "yarn -v",
  "yarn install --immutable"
]

# Build the packages in the right order
[phases.build]
dependsOn = ["install"]
cmds = [
  "cd packages/shared && yarn build",
  "cd ../../packages/server/api && yarn build"
]

# Launch the API service
[start]
cmd = "cd packages/server/api && yarn start"

[variables]
NODE_ENV = "production" 