[phases.setup]
aptPkgs = ["git"]
# Disable Railway's autodetection to prevent it from trying to run its own package manager
nixPkgs = ["nodejs_20"]

# The build and installation commands are now handled by .railway.toml buildCommand
# This is to prevent duplicate/conflicting build processes
[phases.install]
dependsOn = ["setup"]
cmds = [
  "echo 'Setup complete. Build commands will run from .railway.toml buildCommand'"
]

# Build commands are now in .railway.toml buildCommand

# Launch the API service - This is a fallback, as .railway.toml startCommand will be used
[start]
cmd = "cd packages/server/api && yarn start"

# Explicitly disable Railway's automatic package detection
[detect]
# Disable auto-detection for both npm and yarn
NPM = false
YARN = false

[variables]
NODE_ENV = "production" 