[phases.setup]
aptPkgs = ["git"]

# Customize install command but keep corepack intact
[phases.install]
# Default is 'npm install -g corepack@0.24.1 && corepack enable'
dependsOn = ["setup"]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "cd /app && node --version",
  "cd /app && which yarn",
  "cd /app && yarn --version",
  "cd /app && yarn install --no-immutable"
]
targetDir = "/"

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd /app && yarn workspace @wavenotes-new/shared build",
  "cd /app && yarn workspace @wavenotes-new/api build"
]

[start]
cmd = "cd /app/packages/server/api && yarn start"

[variables]
NODE_ENV = "production" 