[phases.setup]
aptPkgs = ["git"]
# Disable Railway's autodetection to prevent it from trying to run its own package manager
nixPkgs = ["nodejs_20"]

# Set up Corepack for Yarn 4 and handle all installation
[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "yarn -v",
  "echo 'Installing dependencies...'",
  "cd /app && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install --mode update-lockfile",
  "echo 'Dependencies installed successfully.'"
]

# Build the packages in the right order
[phases.build]
dependsOn = ["install"]
cmds = [
  # Step 1: Build the shared package 
  "echo '=== Step 1: Building shared package ==='",
  "cd /app/packages/shared && yarn build",
  "echo 'Shared package built successfully:'",
  "ls -la /app/packages/shared/dist",
  
  # Step 2: Build the API package
  "echo '=== Step 2: Building API package ==='", 
  "cd /app/packages/server/api && yarn build",
  "echo 'API package built successfully.'",
  
  # Step 3: Build the worker package
  "echo '=== Step 3: Building worker package ==='",
  "cd /app/packages/server/worker && yarn build",
  "echo 'Worker package built successfully.'",
  
  # Step 4: Prepare deployment environment
  "echo '=== Step 4: Preparing deployment environment ==='",
  
  # Step 5: Ensure modules are properly available
  "echo '=== Step 5: Ensuring modules are available ==='",
  
  # Remove any existing directories to avoid conflicts
  "echo 'Removing any existing package symlinks or directories...'",
  "rm -rf /app/packages/server/worker/node_modules/@wavenotes-new/shared",
  "rm -rf /app/packages/server/worker/node_modules/@wavenotes-new/api",
  
  # Create parent directories if they don't exist
  "mkdir -p /app/packages/server/worker/node_modules/@wavenotes-new",
  
  # Copy the ENTIRE shared package including the dist directory
  "echo 'Copying shared package with all files...'",
  "cp -r /app/packages/shared /app/packages/server/worker/node_modules/@wavenotes-new/",
  
  # Copy the ENTIRE API package including the dist directory
  "echo 'Copying API package with all files...'",
  "cp -r /app/packages/server/api /app/packages/server/worker/node_modules/@wavenotes-new/",
  
  # Critical: Ensure the dist directories were successfully copied
  "echo 'Verifying shared dist directory was correctly copied:'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/shared/dist || echo 'ERROR: shared dist directory not found!'",
  
  "echo 'Verifying API dist directory was correctly copied:'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/api/dist || echo 'ERROR: API dist directory not found!'",
  
  # Ensure package.json has correct main entry for shared
  "echo 'Ensuring shared package.json main entry is correct'",
  "node -e \"const fs=require('fs'); const path='/app/packages/server/worker/node_modules/@wavenotes-new/shared/package.json'; const pkg=JSON.parse(fs.readFileSync(path)); console.log('Current shared main entry:', pkg.main); pkg.main='dist/index.js'; fs.writeFileSync(path, JSON.stringify(pkg, null, 2)); console.log('Updated shared main entry to:', 'dist/index.js');\"",
  
  # Ensure package.json has correct main entry for API
  "echo 'Ensuring API package.json main entry is correct'",
  "node -e \"const fs=require('fs'); const path='/app/packages/server/worker/node_modules/@wavenotes-new/api/package.json'; const pkg=JSON.parse(fs.readFileSync(path)); console.log('Current API main entry:', pkg.main); pkg.main='dist/index.js'; fs.writeFileSync(path, JSON.stringify(pkg, null, 2)); console.log('Updated API main entry to:', 'dist/index.js');\"",
  
  # Verify the final structure and check that index.js files specifically exist
  "echo 'Verifying main index.js files exist:'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/shared/dist/index.js || echo 'ERROR: shared index.js NOT FOUND!'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/api/dist/index.js || echo 'ERROR: API index.js NOT FOUND!'",
  
  # Add a comprehensive test of the module loading
  "echo 'Testing module loading with a simple script:'",
  "echo 'try { const shared = require(\"/app/packages/server/worker/node_modules/@wavenotes-new/shared\"); const api = require(\"/app/packages/server/worker/node_modules/@wavenotes-new/api\"); console.log(\"Shared module loaded successfully!\", Object.keys(shared)); console.log(\"API module loaded successfully!\", Object.keys(api)); } catch (err) { console.error(\"Failed to load modules:\", err); process.exit(1); }' > /app/test-worker-modules.js",
  "cd /app && node test-worker-modules.js"
]

# Launch the Worker service
[start]
cmd = "cd /app/packages/server/worker && NODE_ENV=production node dist/index.js"

# Explicitly disable Railway's automatic package detection
[detect]
# Disable auto-detection for both npm and yarn
NPM = false
YARN = false

[variables]
NODE_ENV = "production" 