[phases.setup]
aptPkgs = ["git"]
# Disable Railway's autodetection to prevent it from trying to run its own package manager
nixPkgs = ["nodejs_20"]

# Set up Corepack for Yarn 4 and handle all installation
[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "yarn -v",
  "echo 'Installing dependencies...'",
  "cd /app && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install --mode update-lockfile",
  "echo 'Dependencies installed successfully.'"
]

# Build the packages in the right order
[phases.build]
dependsOn = ["install"]
cmds = [
  # Step 1: Build the shared package
  "echo '=== Step 1: Building shared package ==='",
  "cd /app/packages/shared && yarn build",
  "echo 'Shared package files:'",
  "ls -la /app/packages/shared/dist",
  
  # Step 2: Build the API package
  "echo '=== Step 2: Building API package ==='", 
  "cd /app/packages/server/api && yarn build",
  "echo 'API package built successfully.'",
  
  # Step 3: Build the worker package
  "echo '=== Step 3: Building worker package ==='",
  "cd /app/packages/server/worker && yarn build",
  "echo 'Worker package built successfully.'",
  
  # Step 4: Set up module resolution - simplified approach
  "echo '=== Step 4: Setting up module resolution ==='",
  
  # Ensure shared package has main entry pointing to dist/index.js
  "echo 'Updating shared package.json main entry'",
  "cd /app/packages/shared && node -e \"const fs=require('fs'); const pkg=JSON.parse(fs.readFileSync('package.json')); pkg.main = 'dist/index.js'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));\"",
  
  # Ensure API package has main entry pointing to dist/index.js
  "echo 'Updating API package.json main entry'",
  "cd /app/packages/server/api && node -e \"const fs=require('fs'); const pkg=JSON.parse(fs.readFileSync('package.json')); pkg.main = 'dist/index.js'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));\"",
  
  # Create a clean node_modules structure
  "echo 'Creating fresh node_modules structure'",
  "mkdir -p /app/packages/server/worker/node_modules/@wavenotes-new",
  
  # Copy the shared package directly into worker's node_modules
  "echo 'Copying shared package to worker node_modules'",
  "cp -r /app/packages/shared /app/packages/server/worker/node_modules/@wavenotes-new/",
  
  # Copy the API package directly into worker's node_modules
  "echo 'Copying API package to worker node_modules'",
  "cp -r /app/packages/server/api /app/packages/server/worker/node_modules/@wavenotes-new/",
  
  # Verify the structure
  "echo 'Verifying node_modules structure:'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/shared",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/shared/dist || echo 'shared dist directory missing!'",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/api",
  "ls -la /app/packages/server/worker/node_modules/@wavenotes-new/api/dist || echo 'api dist directory missing!'",
  
  "echo 'Module resolution setup completed.'"
]

# Launch the Worker service
[start]
cmd = "cd /app/packages/server/worker && NODE_ENV=production node dist/index.js"

# Explicitly disable Railway's automatic package detection
[detect]
# Disable auto-detection for both npm and yarn
NPM = false
YARN = false

[variables]
NODE_ENV = "production" 