[build]
builder = "nixpacks"

[deploy]
startCommand = "cd ./packages/server/api && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[crons.check-timeouts]
schedule = "*/30 * * * *"
command = "yarn workspace @wavenotes-new/api check-timeouts"

# Explicitly disable Dockerfile usage
[build.nixpacks]
enable = true 