[phases.setup]
aptPkgs = ["git"]

# Customize install command but keep corepack intact
[phases.install]
# Default is 'npm install -g corepack@0.24.1 && corepack enable'
# We'll let Railway handle that part and add our own command after
dependsOn = ["setup"]
cmds = ["yarn install --no-immutable"]
targetDir = "/"

[phases.build]
dependsOn = ["install"]
cmds = [
  "yarn workspace @wavenotes-new/shared build",
  "yarn workspace @wavenotes-new/worker build"
]

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production" 